#SPDX-License-Identifier: MIT-0
---
# tasks file for apache
- name: Installing required packages
  ansible.builtin.dnf:
    name:
      - httpd
      - firewalld
    state: present

- name: Starting and Enabling the service
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - httpd
    - firewalld

- name: Allowing http service on firewall
  ansible.posix.firewalld:
    service: http
    state: enabled
    permanent: true
    immediate: true

- name: deploying web page
  ansible.builtin.template:
    src: index.html.j2
    dest: index.html
